// server/src/utils/errorCodes.js
// Defines standardized error codes for API responses and internal errors.

module.exports = {
  // General Server Errors
  SERVER_ERROR: 'SERVER_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  BAD_REQUEST: 'BAD_REQUEST',

  // Authentication Errors
  AUTH_MISSING_TOKEN: 'AUTH_MISSING_TOKEN',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_FAILED: 'AUTH_FAILED',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_WRONG_PASSWORD: 'AUTH_WRONG_PASSWORD',

  // Resource Specific Errors
  CRISIS_NOT_FOUND: 'CRISIS_NOT_FOUND',
  HAZARD_NOT_FOUND: 'HAZARD_NOT_FOUND',
  PERSON_NOT_FOUND: 'PERSON_NOT_FOUND',
  ALERT_NOT_FOUND: 'ALERT_NOT_FOUND',
  SCENARIO_NOT_FOUND: 'SCENARIO_NOT_FOUND',
  SIMULATION_ALREADY_RUNNING: 'SIMULATION_ALREADY_RUNNING',
  SIMULATION_NOT_RUNNING: 'SIMULATION_NOT_RUNNING',
  SIMULATION_NOT_PAUSED: 'SIMULATION_NOT_PAUSED',
  CONFIG_NOT_FOUND: 'CONFIG_NOT_FOUND',
  BUILDING_DATA_ERROR: 'BUILDING_DATA_ERROR',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  NO_SAFE_PATH: 'NO_SAFE_PATH',

  // Database Errors
  DB_CONNECTION_FAILED: 'DB_CONNECTION_FAILED',
  DB_WRITE_FAILED: 'DB_WRITE_FAILED',
  DB_READ_FAILED: 'DB_READ_FAILED',
  DB_VALIDATION_FAILED: 'DB_VALIDATION_FAILED',

  // External Service Errors
  EXTERNAL_SERVICE_UNAVAILABLE: 'EXTERNAL_SERVICE_UNAVAILABLE',
};

